### ISSUE TITLE
Unmet Requirements

### ISSUE THREAD

**Issue by Arcpartners** [charlie-baba/user-api#9]
* Not deployed - Please deploy your solution to a server online e.g Heroku
* No visibility on code quality and test coverage - Please integrate Codacy add the code quality and test coverage badges to the README file if possible

**Comment by charlie-baba** [comment]
The app has been deployed to  Heroku:  https://arc-user-api.herokuapp.com/
The code quality and test coverage has been added
However, jacoco report is not recording the test methods.
I'm looking into it.
